# Generated by Django 5.0.3 on 2024-04-24 02:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodLogger', '0002_foodentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodentry',
            name='created_at',
        ),
        migrations.AddField(
            model_name='foodentry',
            name='log_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
