# Generated by Django 5.0.3 on 2024-05-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodLogger', '0005_weightentry_goal_weight_delete_usersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightentry',
            name='goal_weight',
        ),
    ]
