# Generated by Django 5.0.3 on 2024-05-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodLogger', '0006_remove_weightentry_goal_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightentry',
            name='goal_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
