# Generated by Django 5.0.3 on 2024-05-10 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodLogger', '0007_weightentry_goal_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodentry',
            name='water',
        ),
        migrations.RemoveField(
            model_name='weightentry',
            name='goal_weight',
        ),
    ]
